### PR TITLE
Improve CI workflow

### PR DESCRIPTION
**Pull request by jprinet**
### Improvements
- check generated dist files are consistent with the source code
- end-to-end test of the build scan publication flow
- enforce Maven extension consistency (JDK 11 compiler, Jar metadata)
- group dist files in a folder at the root project level

### Fixes
- capture build scan link in the Maven publish action
- generate summary when build scan link file is absent

### Note
The end-to-end test in the Github build workflow involves fetching an artifact from the current workflow run.
This is only possible with an upgrade of the npm library `actions/artifact@2+` which also brings immutability to the workflow artifacts (see [documentation](https://github.com/actions/toolkit/tree/main/packages/artifact)).
This led to some further changes as the initial implementation was adding files from different job to the same artifact.

In addition to that, the end-to-end test uses specific find options to collect the artifacts.

### CODE REVIEW

**Review by bigdaz — APPROVED** [review]
LGTM

One comment: I think there would be benefits to combining the various 'dist' directories under a common parent, rather than having the split like they are. 

Having all of the generated outputs in one directory would:
- make it easier to skip over these in a code review
- make it easier to avoid committing these "generated" files together with the associated source file changes.

The second point may not seem that important, but it becomes vital if you ever want to rebase/reorganize/merge different commits. The generated outputs are generally impossible to merge, so having these in a single commit makes it easy to exclude that commit and then regenerate after the merge is complete.

**Comment by jprinet** [comment]
> One comment: I think there would be benefits to combining the various 'dist' directories under a common parent, rather than having the split like they are.

I agree with your comment, I'll adjust this in the current PR 👍

**Comment by jprinet** [comment]
> One comment: I think there would be benefits to combining the various 'dist' directories under a common parent, rather than having the split like they are.

I pushed a commit to address that, let me know if you are happy with the changes @bigdaz

**Review by bigdaz — APPROVED** [review]
LGTM

**Pull request merged**
